export const ADD_POST = 'ADD_POST';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_COMPLETE = 'FETCH_POSTS_COMPLETE';

export const ADD_POINTS = 'ADD_POINTS';
export const SUBTRACT_POINTS = 'SUBTRACT_POINTS';
